Traceback (most recent call last):
  File "/Users/zizhenguo/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/zizhenguo/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/zizhenguo/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/zizhenguo/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/zizhenguo/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/zizhenguo/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/zizhenguo/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/zizhenguo/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#ohe_columns = listfun.list_abs(preprocessor, "pipeline-2", "onehotencoder", categorical_features)
ohe_columns = listfun.list_abs(preprocessor, "pipeline-2", "onehotencoder", categorical_features)
ohe_columns2 = listfun.list_abs(preprocessor, "pipeline-3", "onehotencoder", binary_features)

new_columns = numeric_features + ohe_columns + ohe_columns2

df_coeff = pd.DataFrame(
    data={
        "features": new_columns,
        "coefficients": pipelr2.named_steps["ridge"].coef_,
    }
)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m<ipython-input-14-b316666dd121>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m#ohe_columns = listfun.list_abs(preprocessor, "pipeline-2", "onehotencoder", categorical_features)[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mohe_columns[0m [0;34m=[0m [0mlistfun[0m[0;34m.[0m[0mlist_abs[0m[0;34m([0m[0mpreprocessor[0m[0;34m,[0m [0;34m"pipeline-2"[0m[0;34m,[0m [0;34m"onehotencoder"[0m[0;34m,[0m [0mcategorical_features[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m [0mohe_columns2[0m [0;34m=[0m [0mlistfun[0m[0;34m.[0m[0mlist_abs[0m[0;34m([0m[0mpreprocessor[0m[0;34m,[0m [0;34m"pipeline-3"[0m[0;34m,[0m [0;34m"onehotencoder"[0m[0;34m,[0m [0mbinary_features[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0;34m[0m[0m
[1;32m      5[0m [0mnew_columns[0m [0;34m=[0m [0mnumeric_features[0m [0;34m+[0m [0mohe_columns[0m [0;34m+[0m [0mohe_columns2[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/Desktop/DSCI-310-Group-1/src/listfun.py[0m in [0;36mlist_abs[0;34m(pre, transformers, steps, features)[0m
[1;32m     22[0m     [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     23[0m         ret = list(
[0;32m---> 24[0;31m         [0mpre[0m[0;34m.[0m[0mnamed_transformers_[0m[0;34m[[0m[0mtransformers[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     25[0m         [0;34m.[0m[0mnamed_steps[0m[0;34m[[0m[0msteps[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m     26[0m         [0;34m.[0m[0mget_feature_names_out[0m[0;34m([0m[0mfeatures[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mAttributeError[0m: 'OneHotEncoder' object has no attribute 'get_feature_names_out'
AttributeError: 'OneHotEncoder' object has no attribute 'get_feature_names_out'

